import { Inter } from "next/font/google";
import Navbar from "../components/navigation/Navbar";
import FooterComponent from "../components/footer/Footer";
import Layout from "../components/Layout";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Navbar />
          {children}
          <FooterComponent />
        </Layout>
      </body>
    </html>
  );
}
